### ISSUE TITLE
Group doesn't generated for single sidenote

### ISSUE THREAD

**Issue by ptzn** [acdlite/jquery.sidenotes#4]
Sidenote created without group element for html like this:

``` html
<article class="post">
  <p class="pivot">Lorem ipsum dolor sit amet, consectetur adipisicing elit. Consequatur, odit, maxime, eos nobis molestias quod modi voluptas quibusdam doloremque repellendus quasi illo veritatis ullam eius magnam nemo iste ipsam autem.<sup id="fnref:only-one"><a href="#fn:only-one" class="footnote">1</a></sup> Aliquam, alias, quo id aperiam atque accusantium repellat enim explicabo sed illum cumque iure possimus vero cupiditate officia nesciunt autem reiciendis expedita tenetur ut est accusamus non provident ea voluptatem itaque molestiae ducimus distinctio soluta tempora sapiente similique perspiciatis dolor voluptatum sint quibusdam porro pariatur architecto vel consequatur!</p>

  <div class="footnotes footnote-container">
    <ol class="footnote-list">
      <li id="fn:only-one">
        <p>First and only note. <a href="#fnref:only-one" class="reversefootnote">&#8617;</a></p>
      </li>
    </ol>
  </div>
</article>
```

In jquery.sidenotes.coffee line 155 script check previous sidenote existent and if not exist (it's our case) group not created at all. I've tried fix this issue by myself, but my fix broke other tests, so I gave up.

**Comment by acdlite** [comment]
This is the intended behavior. Groups are only generated for two or more adjacent sidenotes. Could you please explain in more detail what you're trying to do?

You may find the `formatSidenote` option useful. Check the source for documentation. It allows you to control the markup of the sidenotes.

**Comment by ptzn** [comment]
Ah, ok.

I have a TABLE with portions of texts. Each text wrapped with TD and I need to place sidenotes into special TD right after text. Problem is I don't know how many sidenotes will contain these texts and when I see different behavior depends on sidenotes count it's a little bit annoying.

I patch library to make it suitable with my requirements, because I just need group to be generated even for single sidenote and formatSidenote is about sidenotes formatting.

So you can ignore this issue and close it as it not a bug :)

**Comment by acdlite** [comment]
Okay! Just for clarification, the purpose of the sidenote groups is to preserve order when switching `sidenotePlacement`. They aren't added to single sidenotes because they aren't necessary.

The reason I suggested using `formatSidenote` is because you could use it to wrap each sidenote in an additional wrapper element (or whatever extra markup you need). However, if it's easier for you to just patch it for your own needs, of course you should do that. :)
